ip: 127.0.0.1
host_ip: 0.0.0.0
port: 25555
name: John
player_color_hue: 120.0
sens: 0.003
qe_sens: 3.0
sound: false
keybindings:
  Fire1:
  - !MouseButton Left
  Special1:
  - !KeyCode KeyQ
  Descend:
  - !KeyCode ShiftLeft
  Mod3:
  - !KeyCode AltLeft
  - !KeyCode AltRight
  Escape:
  - !KeyCode Escape
  Special2:
  - !KeyCode KeyE
  MoveForward:
  - !KeyCode KeyW
  MoveBackward:
  - !KeyCode KeyS
  StrafeRight:
  - !KeyCode KeyD
  Special3:
  - !KeyCode KeyF
  OpenInventory:
  - !KeyCode KeyI
  - !KeyCode Tab
  Mod2:
  - !KeyCode ControlLeft
  - !KeyCode ControlRight
  Jump:
  - !KeyCode Space
  Chat:
  - !KeyCode Enter
  StrafeLeft:
  - !KeyCode KeyA
  Mod1:
  - !KeyCode ShiftLeft
  - !KeyCode ShiftRight
  Ascend:
  - !KeyCode Space
  Fire2:
  - !MouseButton Right
  ZoomCameraOut:
  - !KeyCode Minus
  ZoomCameraIn:
  - !KeyCode Equal
  Scoreboard:
  - !KeyCode KeyP
