ip: 127.0.0.1
host_ip: 0.0.0.0
port: 25555
name: John 
sens: 0.003
qe_sens: 3.0
sound: false
keybindings:
  Jump:
  - !KeyCode Space
  Fire2:
  - !KeyCode KeyQ
  - !MouseButton Right
  StrafeLeft:
  - !KeyCode KeyA
  Use:
  - !KeyCode KeyE
  RotateLeft:
  - !KeyCode KeyQ
  RotateRight:
  - !KeyCode KeyE
  ChangeCamera:
  - !KeyCode KeyC
  UnlockCursor:
  - !KeyCode KeyX
  MoveForward:
  - !KeyCode KeyW
  Mod1:
  - !KeyCode ShiftLeft
  MoveBackward:
  - !KeyCode KeyS
  StrafeRight:
  - !KeyCode KeyD
  Fire1:
  - !MouseButton Left
  Chat:
  - !KeyCode Enter
